// leste des produits Pokémon
export const pokemonProducts = [
  // jeux
  { id: 'pg1', title: 'Pokémon Blue', price: 49.99, category: 'games', image: '/assets/games/game_blue.jpg', description: 'Explora a região de Kanto e torna-te no melhor treinador! Captura o lendário Blastoise e derrota a Elite Quatro nesta aventura épica que marcou uma geração.' },
  { id: 'pg2', title: 'Pokémon Red', price: 49.99, category: 'games', image: '/assets/games/game_red.jpg', description: 'O início de uma lenda! Embarca numa jornada inesquecível com Charizard ao teu lado e desafia o teu rival para te tornares o Campeão de Kanto.' },
  { id: 'pg3', title: 'Pokémon Yellow', price: 49.99, category: 'games', image: '/assets/games/game_yellow.png', description: 'A edição especial Pikachu! O teu fiel companheiro elétrico segue-te por todo o lado enquanto revives a magia do anime original.' },
  { id: 'pg4', title: 'Pokémon Gold', price: 59.99, category: 'games', image: '/assets/games/game_gold.jpg', description: 'Descobre a mágica região de Johto! Com o ciclo dia/noite e o lendário Ho-Oh, esta aventura leva-te a novos horizontes.' },
  { id: 'pg5', title: 'Pokémon Silver', price: 59.99, category: 'games', image: '/assets/games/game_silver.png', description: 'Encontra Lugia nas profundezas do oceano! Explora Johto e regressa a Kanto nesta épica aventura dupla.' },
  { id: 'pg6', title: 'Pokémon Crystal', price: 69.99, category: 'games', image: '/assets/games/game_crystal.png', description: 'A primeira aventura com protagonista feminina! Desvenda os mistérios dos Unown e encontra o majestoso Suicune.' },
  { id: 'pg7', title: 'Pokémon Ruby', price: 39.99, category: 'games', image: '/assets/games/game_ruby.png', description: 'Bem-vindo a Hoenn! Enfrenta a Team Magma e desperta o poder primordial de Groudon nesta aventura tropical.' },
  { id: 'pg8', title: 'Pokémon Sapphire', price: 39.99, category: 'games', image: '/assets/games/game_sapphire.jpg', description: 'A Team Aqua está a despertar! Mergulha nas profundezas do oceano e conhece o lendário Kyogre.' },
  { id: 'pg9', title: 'Pokémon Emerald', price: 45.99, category: 'games', image: '/assets/games/game_emerald.jpg', description: 'Rayquaza desce dos céus! A versão definitiva de Hoenn com a Battle Frontier e duplas batalhas épicas.' },
  { id: 'pg10', title: 'Pokémon FireRed', price: 49.99, category: 'games', image: '/assets/games/game_firered.jpg', description: 'Kanto renasce a cores! Revive a aventura clássica com gráficos renovados e as Sevii Islands para explorar.' },
  { id: 'pg11', title: 'Pokémon LeafGreen', price: 49.99, category: 'games', image: '/assets/games/game_leafgreen.jpg', description: 'A nostalgia em tons de verde! Volta a Kanto com Bulbasaur e descobre novos segredos escondidos.' },
  { id: 'pg12', title: 'Pokémon Diamond', price: 39.99, category: 'games', image: '/assets/games/game_diamond.jpg', description: 'Dialga controla o tempo! Explora Sinnoh e enfrenta a misteriosa Team Galactic nesta aventura cósmica.' },
  { id: 'pg13', title: 'Pokémon Pearl', price: 39.99, category: 'games', image: '/assets/games/game_pearl.jpg', description: 'Palkia distorce o espaço! Viaja por Sinnoh e descobre os segredos do Monte Corona.' },
  { id: 'pg14', title: 'Pokémon Platinum', price: 49.99, category: 'games', image: '/assets/games/game_platinum.png', description: 'Entra no Mundo Distorcido! Giratina aguarda-te numa aventura que desafia as leis da realidade.' },
  { id: 'pg15', title: 'Pokémon HeartGold', price: 59.99, category: 'games', image: '/assets/games/game_heartgold.jpg', description: 'Johto reimaginado! Com o Pokéwalker, o teu Pokémon acompanha-te no mundo real nesta obra-prima nostálgica.' },
  { id: 'pg16', title: 'Pokémon SoulSilver', price: 59.99, category: 'games', image: '/assets/games/game_soulsilver.jpg', description: 'Lugia regressa em glória! A versão definitiva da aventura em Johto com duas regiões completas para explorar.' },
  { id: 'pg17', title: 'Pokémon Black', price: 49.99, category: 'games', image: '/assets/games/game_black.jpg', description: 'Verdade ou Ideais? Embarca numa história profunda em Unova e conhece Reshiram, o dragão da verdade.' },
  { id: 'pg18', title: 'Pokémon White', price: 49.99, category: 'games', image: '/assets/games/game_white.webp', description: 'Zekrom, o dragão dos ideais! Uma narrativa madura que questiona a relação entre humanos e Pokémon.' },
  { id: 'pg19', title: 'Pokémon Black 2', price: 59.99, category: 'games', image: '/assets/games/game_black2.webp', description: 'Dois anos depois em Unova! A primeira sequela direta traz novas áreas, novos desafios e Kyurem Negro.' },
  { id: 'pg20', title: 'Pokémon White 2', price: 59.99, category: 'games', image: '/assets/games/pokemon_white2.webp', description: 'A saga de Unova continua! Descobre o destino de N e enfrenta Kyurem Branco nesta aventura emocionante.' },
  { id: 'pg21', title: 'Pokémon X', price: 39.99, category: 'games', image: '/assets/games/game_x.jpg', description: 'A Mega Evolução chegou! Explora a elegante região de Kalos inspirada em França e conhece Xerneas.' },
  { id: 'pg22', title: 'Pokémon Y', price: 39.99, category: 'games', image: '/assets/games/game_y.jpg', description: 'Yveltal levanta voo! Em 3D pela primeira vez, Kalos oferece uma aventura visualmente deslumbrante.' },
  { id: 'pg23', title: 'Pokémon Omega Ruby', price: 39.99, category: 'games', image: '/assets/games/game_omegaruby.jpg', description: 'Groudon Primordial desperta! Hoenn renascido em 3D com Mega Evoluções e o Delta Episode épico.' },
  { id: 'pg24', title: 'Pokémon Alpha Sapphire', price: 39.99, category: 'games', image: '/assets/games/game_alphasapphire.jpg', description: 'Kyogre Primordial emerge! Mergulha nas profundezas renovadas de Hoenn e voa pelos céus em Latias.' },
  { id: 'pg25', title: 'Pokémon Sun', price: 39.99, category: 'games', image: '/assets/games/game_sun.jpg', description: 'Aloha, bem-vindo a Alola! Troca ginásios por Provas Insulares e conhece Solgaleo, a emanação do sol.' },
  { id: 'pg26', title: 'Pokémon Moon', price: 39.99, category: 'games', image: '/assets/games/game_moon.jpg', description: 'Lunala ilumina a noite! Descobre os Ultra Beasts e a cultura tropical única de Alola.' },
  { id: 'pg27', title: 'Pokémon Ultra Sun', price: 44.99, category: 'games', image: '/assets/games/game_ultrasun.jpg', description: 'Necrozma ataca! A versão expandida com Ultra Warp Ride, novos Pokémon e história alternativa.' },
  { id: 'pg28', title: 'Pokémon Ultra Moon', price: 44.99, category: 'games', image: '/assets/games/game_ultramoon.webp', description: 'Alola em perigo! Viaja pelo Ultra Espaço e enfrenta os Ultra Recon Squad nesta aventura cósmica.' },
  { id: 'pg29', title: 'Pokémon Let\'s Go Pikachu', price: 59.99, category: 'games', image: '/assets/games/game_letsgopikachu.jpg', description: 'Kanto reimaginado para Switch! Pikachu no teu ombro, mecânicas de Pokémon GO e nostalgia pura.' },
  { id: 'pg30', title: 'Pokémon Let\'s Go Eevee', price: 59.99, category: 'games', image: '/assets/games/game_letsgoeevee.png', description: 'Eevee é a tua estrela! Com penteados personalizáveis e técnicas secretas, esta aventura é adorável.' },
  { id: 'pg31', title: 'Pokémon Sword', price: 59.99, category: 'games', image: '/assets/games/game_sword.webp', description: 'Bem-vindo a Galar! Dynamax, Wild Area e estádios cheios de adeptos esperam-te nesta aventura britânica.' },
  { id: 'pg32', title: 'Pokémon Shield', price: 59.99, category: 'games', image: '/assets/games/game_shield.webp', description: 'Defende Galar! Com Pokémon exclusivos e raids cooperativos, esta é a experiência definitiva na Switch.' },
  { id: 'pg33', title: 'Pokémon Brilliant Diamond', price: 59.99, category: 'games', image: '/assets/games/game_brilliantdiamond.png', description: 'Sinnoh renasce em estilo chibi! Revive a aventura clássica com o Grand Underground expandido.' },
  { id: 'pg34', title: 'Pokémon Shining Pearl', price: 59.99, category: 'games', image: '/assets/games/game_shinningpearl.png', description: 'Palkia brilha novamente! A nostalgia de Sinnoh com melhorias de qualidade de vida modernas.' },
  { id: 'pg35', title: 'Pokémon Legends: Arceus', price: 59.99, category: 'games', image: '/assets/games/game_arceus.jpg', description: 'A história antiga de Sinnoh! Um RPG de ação revolucionário que muda tudo o que conhecias sobre Pokémon.' },
  { id: 'pg36', title: 'Pokémon Scarlet', price: 59.99, category: 'games', image: '/assets/games/game_scarlet.jpg', description: 'Mundo aberto em Paldea! Com Koraidon, três histórias épicas e o fenómeno Terastal aguardam-te.' },
  { id: 'pg37', title: 'Pokémon Violet', price: 59.99, category: 'games', image: '/assets/games/game_violet.jpg', description: 'O futuro chegou a Paldea! Miraidon leva-te numa aventura tecnológica de mundo aberto sem precedentes.' },
  { id: 'pg38', title: 'Pokémon Legends: Z-A', price: 59.99, category: 'games', image: '/assets/games/game_za.jpg', description: 'Regressa a Kalos! Uma nova aventura Legends ambientada na cidade de Lumiose com segredos por descobrir.' },

  // DLC
  { id: 'pd1', title: 'Scarlet & Violet DLC', price: 34.99, category: 'dlc', image: '/assets/dlc/dlc_scarletviolet.jpg', description: 'O Tesouro Oculto da Área Zero! Duas expansões épicas com Kitakami e a Academia Mirtilo.' },
  { id: 'pd2', title: 'Sword & Shield DLC', price: 29.99, category: 'dlc', image: '/assets/dlc/dlc_swordshield.jpg', description: 'Expansion Pass completo! A Ilha da Armadura e as Terras da Coroa expandem Galar ao máximo.' },
  { id: 'pd3', title: 'Legends Z-A DLC', price: 29.99, category: 'dlc', image: '/assets/dlc/dlc_ZA.jpg', description: 'Conteúdo adicional para Z-A! Novos mistérios de Kalos aguardam os mais destemidos.' },

  // peluches
  { id: 'pp1', title: 'Absol Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_absol.jpg', description: 'O prenunciador de desastres! Este Absol fofinho traz apenas boa sorte para a tua coleção.' },
  { id: 'pp2', title: 'Ampharos Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_ampharos.jpg', description: 'A luz que guia os marinheiros! Este Ampharos ilumina qualquer divisão com a sua fofura.' },
  { id: 'pp3', title: 'Arcanine Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_arcanine.jpg', description: 'O cão lendário de fogo! Majestoso e fofo, este Arcanine é o guardião perfeito para a tua casa.' },
  { id: 'pp4', title: 'Buizel Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_buizel.jpg', description: 'A lontra marinha aventureira! Com a sua boia no pescoço, está sempre pronto para nadar.' },
  { id: 'pp5', title: 'Celebi Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_celebi.jpg', description: 'O viajante do tempo! Esta fada mística traz paz e serenidade de outras eras.' },
  { id: 'pp6', title: 'Chespin Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_chespin.jpg', description: 'O ouriço de Kalos! Com a sua casca protetora, é tão resistente quanto adorável.' },
  { id: 'pp7', title: 'Cinccino Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_cinccino.jpg', description: 'O pelúcia mais macio! O cachecol de Cinccino é famoso pela sua textura sedosa.' },
  { id: 'pp8', title: 'Cubone Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_cubone.jpg', description: 'O órfão corajoso! Apesar da sua história triste, este Cubone só quer dar abraços.' },
  { id: 'pp9', title: 'Cyndaquil Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_cyndaquil.jpg', description: 'O rato de fogo tímido! Quando ganha confiança, as suas chamas brilham com força.' },
  { id: 'pp10', title: 'Ditto Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_ditto.jpg', description: 'Transforma-se em tudo! Este Ditto sorridente é o companheiro versátil por excelência.' },
  { id: 'pp11', title: 'Eevee Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_eevee.jpg', description: 'Potencial ilimitado! Antes de evoluir, Eevee é pura fofura e possibilidades infinitas.' },
  { id: 'pp12', title: 'Fennekin Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_fennekin.jpg', description: 'A raposa mágica de Kalos! As suas orelhas libertam ar quente para te aquecer.' },
  { id: 'pp13', title: 'Flareon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_flareon.jpg', description: 'O Eeveelution de fogo! Perfeito para abraçar nas noites frias de inverno.' },
  { id: 'pp14', title: 'Floatzel Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_floatzel.jpg', description: 'O salva-vidas aquático! A sua boia inflável está sempre pronta para resgates.' },
  { id: 'pp15', title: 'Glaceon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_glaceon.jpg', description: 'Elegância gelada! Este Glaceon traz a frescura do inverno para a tua coleção.' },
  { id: 'pp16', title: 'Hoopa Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_hoopa.jpg', description: 'O Pokémon travesso! Os seus portais mágicos podem trazer surpresas de todo o mundo.' },
  { id: 'pp17', title: 'Jigglypuff Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_jigglypuff.jpg', description: 'O balão cantor! Cuidado para não adormeceres com a sua canção de embalar.' },
  { id: 'pp18', title: 'Jirachi Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_jirachi.jpg', description: 'Realiza desejos! Este Jirachi adormecido pode tornar os teus sonhos realidade.' },
  { id: 'pp19', title: 'Jolteon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_jolteon.jpg', description: 'Eletricidade pura! Os pelos espetados de Jolteon são surpreendentemente macios.' },
  { id: 'pp20', title: 'Keldeo Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_keldeo.jpg', description: 'O potro espadachim! Treina com as Espadas da Justiça para proteger os inocentes.' },
  { id: 'pp21', title: 'Lapras Plush', price: 39.99, category: 'plush', image: '/assets/plush/plush_lapras.jpg', description: 'O transportador gentil! Lapras leva-te pelos mares com a sua canção melancólica.' },
  { id: 'pp22', title: 'Leafeon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_leafeon.jpg', description: 'Natureza em forma de Eevee! Faz fotossíntese e purifica o ar à tua volta.' },
  { id: 'pp23', title: 'Liepard Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_liepard.jpg', description: 'O felino misterioso! Elegante e sorrateiro, é o companheiro perfeito para a noite.' },
  { id: 'pp24', title: 'Litten Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_litten.jpg', description: 'O gato de fogo independente! Pode parecer distante, mas adora carinho secretamente.' },
  { id: 'pp25', title: 'Litwick Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_litwick.jpg', description: 'A vela fantasma! Esta chama roxa ilumina caminhos escuros com um brilho sobrenatural.' },
  { id: 'pp26', title: 'Lycanroc Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_lycanroc.jpg', description: 'O lobo da meia-noite! Forma noturna com olhos vermelhos e atitude feroz.' },
  { id: 'pp27', title: 'Lycanroc Midday Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_lycanrocmidday.jpg', description: 'O lobo diurno! Leal ao seu treinador, corre mais rápido que o vento.' },
  { id: 'pp28', title: 'Marshadow Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_marshadow.jpg', description: 'O habitante das sombras! Esconde-se nas trevas mas tem um coração de ouro.' },
  { id: 'pp29', title: 'Mew Plush', price: 39.99, category: 'plush', image: '/assets/plush/plush_mew.jpg', description: 'O ancestral de todos! Brincalhão e raro, Mew contém o ADN de todos os Pokémon.' },
  { id: 'pp30', title: 'Mimikyu Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_mimikyu.jpg', description: 'O disfarce adorável! Só quer ser amado como Pikachu. Dá-lhe o carinho que merece!' },
  { id: 'pp31', title: 'Mudbray Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_mudbray.jpg', description: 'O burro trabalhador! Pequeno mas forte, adora brincar na lama.' },
  { id: 'pp32', title: 'Noibat Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_noibat.jpg', description: 'O morcego sonoro! As suas orelhas gigantes captam todos os sons do mundo.' },
  { id: 'pp33', title: 'Oshawott Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_oshawott.jpg', description: 'A lontra samurai! A sua concha scalchop é uma arma e utensílio de cozinha.' },
  { id: 'pp34', title: 'Pichu Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_pichu.jpg', description: 'O bebé elétrico! Ainda não controla bem a eletricidade e dá choques quando feliz.' },
  { id: 'pp35', title: 'Piplup Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_piplup.jpg', description: 'O pinguim orgulhoso! Caminha desajeitadamente mas nada com elegância régia.' },
  { id: 'pp36', title: 'Popplio Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_popplio.jpg', description: 'O leão-marinho artista! Cria bolhas coloridas e sonha em ser uma estrela.' },
  { id: 'pp37', title: 'Purrloin Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_purrloin.jpg', description: 'O gato malandro! Com olhos irresistíveis, engana qualquer um para conseguir o que quer.' },
  { id: 'pp38', title: 'Raichu Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_raichu.jpg', description: 'Pikachu evoluído! A sua cauda descarrega eletricidade suficiente para iluminar uma cidade.' },
  { id: 'pp39', title: 'Alolan Raichu Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_raichualola.jpg', description: 'O surfista elétrico! Flutua na sua cauda e come panquecas em Alola.' },
  { id: 'pp40', title: 'Rockruff Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_rockruff.jpg', description: 'O cachorrinho de Alola! Sociável e leal, é o companheiro perfeito para aventuras.' },
  { id: 'pp41', title: 'Rowlet Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_rowlet.jpg', description: 'A coruja redonda! Guarda sementes nas asas e voa silenciosamente na noite.' },
  { id: 'pp42', title: 'Shaymin Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_shaymin.jpg', description: 'O Pokémon da gratidão! Transforma terras estéreis em campos floridos.' },
  { id: 'pp43', title: 'Sky Shaymin Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_shayminsky.jpg', description: 'Shaymin na forma celeste! Com a Gracidea, voa pelos céus espalhando felicidade.' },
  { id: 'pp44', title: 'Shinx Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_shinx.jpg', description: 'O leãozinho elétrico! O seu pelo brilha quando gera eletricidade.' },
  { id: 'pp45', title: 'Sylveon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_sylveon.jpg', description: 'O Eeveelution fada! As suas fitas sentem as emoções e acalmam conflitos.' },
  { id: 'pp46', title: 'Togedemaru Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_togedemaru.jpg', description: 'O ouriço rolante! Enrola-se numa bola elétrica para se defender.' },
  { id: 'pp47', title: 'Umbreon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_umbreon.jpg', description: 'O guardião da lua! Os anéis brilham dourados sob o luar da meia-noite.' },
  { id: 'pp48', title: 'Vaporeon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_vaporeon.jpg', description: 'O Eeveelution aquático! Derrete na água e reaparece onde menos esperas.' },
  { id: 'pp49', title: 'Victini Plush', price: 39.99, category: 'plush', image: '/assets/plush/plush_victini.jpg', description: 'O Pokémon da vitória! Quem o abraçar nunca mais perde nada na vida.' },
  { id: 'pp50', title: 'Vulpix Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_vulpix.jpg', description: 'A raposa de fogo! As suas seis caudas ondulam como chamas numa brisa suave.' },
  { id: 'pp51', title: 'Wooper Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_wooper.jpg', description: 'O axolote sorridente! Vive feliz na lama e tem o sorriso mais puro do mundo.' },
  { id: 'pp52', title: 'Wynaut Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_wynaut.jpg', description: 'Porque não? Este Pokémon sempre sorri e espalha alegria por onde passa.' },
  { id: 'pp53', title: 'Zeraora Plush', price: 39.99, category: 'plush', image: '/assets/plush/plush_zeraora.jpg', description: 'O trovão personificado! Move-se à velocidade do relâmpago e gera tempestades.' },
  { id: 'pp54', title: 'Zorua Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_zorua.jpg', description: 'A raposa ilusionista! Transforma-se em pessoas e Pokémon para fazer travessuras.' },
  { id: 'pp55', title: 'Meowstic Plush', price: 24.99, category: 'plush', image: '/assets/plush/plus_meowstic.jpg', description: 'O gato psíquico! Os olhos escondidos nas orelhas têm poderes telecinéticos.' },

  // chaussettes
  { id: 'ps1', title: 'Eevee Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_eevee.jpg', description: 'Meias aconchegantes com padrão Eevee! Perfeitas para manter os pés quentinhos e fofos.' },
  { id: 'ps2', title: 'Espeon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_espeon.jpg', description: 'Estilo psíquico para os teus pés! A elegância de Espeon em cada passo que dás.' },
  { id: 'ps3', title: 'Flareon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_flareon.jpg', description: 'Aquece os pés com chama! Estas meias Flareon são perfeitas para os dias frios.' },
  { id: 'ps4', title: 'Glaceon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_glaceon.jpg', description: 'Frescura gelada para os teus pés! O conforto refrescante de Glaceon.' },
  { id: 'ps5', title: 'Jolteon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_jolteon.jpg', description: 'Energia elétrica nos teus passos! Carrega as tuas aventuras com Jolteon.' },
  { id: 'ps6', title: 'Leafeon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_leafeon.jpg', description: 'Sensação natural e ecológica! Leafeon traz a floresta para os teus pés.' },
  { id: 'ps7', title: 'Sylveon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_sylveon.jpg', description: 'Fofura de fada! As fitas de Sylveon envolvem os teus pés com carinho.' },
  { id: 'ps8', title: 'Umbreon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_umbreon.jpg', description: 'Modo noturno ativado! Os anéis brilham no escuro para passeios noturnos.' },
  { id: 'ps9', title: 'Vaporeon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_vaporeon.jpg', description: 'Design aquático refrescante! Vaporeon mantém os teus pés frescos e estilosos.' },

  // supérieurs
  { id: 'pt1', title: 'Arcanine Tee', price: 24.99, category: 'tops', image: '/assets/tops/top_arcanine.jpg', description: 'Estilo lendário! Veste a majestade do cão de fogo mais imponente de Kanto.' },
  { id: 'pt2', title: 'Friends & Foliage Tee', price: 22.99, category: 'tops', image: '/assets/tops/top_friendsfoliage.jpg', description: 'Para amantes da natureza! Pokémon e folhagem num design harmonioso e sereno.' },
  { id: 'pt3', title: 'Glaceon Top', price: 24.99, category: 'tops', image: '/assets/tops/top_glaceon.jpg', description: 'Moda gelada e elegante! Glaceon traz frescura ao teu guarda-roupa.' },
  { id: 'pt4', title: 'Jirachi Tee', price: 25.99, category: 'tops', image: '/assets/tops/top_jirachi.jpg', description: 'Pede um desejo! Esta t-shirt Jirachi realiza o sonho de qualquer fã.' },
  { id: 'pt5', title: 'Jirachi Special Top', price: 27.99, category: 'tops', image: '/assets/tops/top_jirachi2.jpg', description: 'Design cintilante especial! Jirachi brilha como as estrelas nesta edição.' },
  { id: 'pt6', title: 'Lapras Top', price: 26.99, category: 'tops', image: '/assets/tops/top_lapras.jpg', description: 'Navegador dos mares! Lapras leva-te numa viagem oceânica de estilo.' },
  { id: 'pt7', title: 'Leafeon Top', price: 24.99, category: 'tops', image: '/assets/tops/top_leafeon.jpg', description: 'Estética verde e natural! Leafeon purifica o teu visual com elegância.' },
  { id: 'pt8', title: 'Lucario Top', price: 26.99, category: 'tops', image: '/assets/tops/top_lucario.jpg', description: 'Mestre da aura! Sente o poder de Lucario em cada fibra desta t-shirt.' },
  { id: 'pt9', title: 'Mega Charizard Top', price: 29.99, category: 'tops', image: '/assets/tops/top_mega charizard.jpg', description: 'Poder Mega ativado! Charizard na sua forma mais poderosa e imponente.' },
  { id: 'pt10', title: 'Mimikyu Top', price: 24.99, category: 'tops', image: '/assets/tops/top_mimikyu.jpg', description: 'O amigo misterioso! Mimikyu só quer ser amado, e tu vais adorar esta camisola.' },
  { id: 'pt11', title: 'Ninetales Top', price: 25.99, category: 'tops', image: '/assets/tops/top_ninetales.jpg', description: 'Fogo elegante e místico! As nove caudas de Ninetales dançam neste design.' },
  { id: 'pt12', title: 'Sylveon Top', price: 24.99, category: 'tops', image: '/assets/tops/top_sylveon.jpg', description: 'Fitas de fada! Sylveon envolve-te em magia e fofura encantadora.' },
  { id: 'pt13', title: 'Tropical Top', price: 22.99, category: 'tops', image: '/assets/tops/top_tropical.jpg', description: 'Vibrações de verão! Pokémon tropicais para os dias mais quentes.' },
  { id: 'pt14', title: 'Tropical Dreamy Top', price: 23.99, category: 'tops', image: '/assets/tops/top_tropicaldreamy.jpg', description: 'Vida de ilha! Um sonho tropical Pokémon para vestir todo o ano.' },
  { id: 'pt15', title: 'Umbreon Top', price: 24.99, category: 'tops', image: '/assets/tops/top_umbreon.jpg', description: 'Lua negra! Umbreon brilha na escuridão com o seu visual noturno.' },
  { id: 'pt16', title: 'Zorua Top', price: 23.99, category: 'tops', image: '/assets/tops/top_zorua.jpg', description: 'Ilusão de raposa! Zorua transforma o teu look com mistério e charme.' },

  // inférieurs
  { id: 'pb1', title: 'Glimwood Bottoms', price: 34.99, category: 'bottom', image: '/assets/bottom/bottom glimwood.jpg', description: 'Estilo da floresta mística! Inspirado na Glimwood Tangle de Galar.' },
  { id: 'pb2', title: 'Sylveon Shorts', price: 29.99, category: 'bottom', image: '/assets/bottom/bottom sylveon.jpg', description: 'Calções com fitas fofas! Sylveon traz elegância e conforto aos teus dias.' },
  { id: 'pb3', title: 'Friends & Foliage Shorts', price: 29.99, category: 'bottom', image: '/assets/bottom/bottom_friendsfoliage.jpg', description: 'Festa no jardim! Pokémon e natureza em perfeita harmonia para os teus passeios.' },
  { id: 'pb4', title: 'Jigglypuff Leggings', price: 32.99, category: 'bottom', image: '/assets/bottom/bottom_jigglypuff.jpg', description: 'Canta e dança! Leggings Jigglypuff para treinos ou momentos de lazer.' },
  { id: 'pb5', title: 'Pikachu Joggers', price: 39.99, category: 'bottom', image: '/assets/bottom/bottom_pikachu.jpg', description: 'Velocidade elétrica! Joggers Pikachu para correr à velocidade do relâmpago.' },
  { id: 'pb6', title: 'Tropical Bottoms', price: 34.99, category: 'bottom', image: '/assets/bottom/bottom_tropical.jpg', description: 'Pronto para a praia! Calças tropicais para as tuas aventuras de verão.' },
  { id: 'pb7', title: 'Tropical Dreamy Shorts', price: 29.99, category: 'bottom', image: '/assets/bottom/bottom_tropicaldreamy.jpg', description: 'Modo férias! Calções de sonho para os dias mais descontraídos.' },
  { id: 'pb8', title: 'Zorua Pants', price: 36.99, category: 'bottom', image: '/assets/bottom/bottom_zorua.jpg', description: 'Caminhante das sombras! Calças Zorua para um look misterioso e estiloso.' },
];

// chercher des produits avec un délai simulé
export const getPokemonProducts = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
        resolve(pokemonProducts);
    }, 500); // délai réseau simulé
  });
};
