export const pokemonProducts = [
  // Games
  { id: 'pg1', title: 'Pokémon Blue', price: 49.99, category: 'games', image: '/assets/games/game_blue.jpg', description: 'Explore Kanto and defeat the Elite Four.' },
  { id: 'pg2', title: 'Pokémon Red', price: 49.99, category: 'games', image: '/assets/games/game_red.jpg', description: 'The start of the legendary journey.' },
  { id: 'pg3', title: 'Pokémon Yellow', price: 49.99, category: 'games', image: '/assets/games/game_yellow.png', description: 'Special Pikachu Edition.' },
  { id: 'pg4', title: 'Pokémon Gold', price: 59.99, category: 'games', image: '/assets/games/game_gold.jpg', description: 'Adventure in Johto.' },
  { id: 'pg5', title: 'Pokémon Silver', price: 59.99, category: 'games', image: '/assets/games/game_silver.png', description: 'Encounter Lugia.' },
  { id: 'pg6', title: 'Pokémon Crystal', price: 69.99, category: 'games', image: '/assets/games/game_crystal.png', description: 'Unlock the mysteries of the Unown.' },
  { id: 'pg7', title: 'Pokémon Ruby', price: 39.99, category: 'games', image: '/assets/games/game_ruby.png', description: 'Hoenn region awaits.' },
  { id: 'pg8', title: 'Pokémon Sapphire', price: 39.99, category: 'games', image: '/assets/games/game_sapphire.jpg', description: 'Team Aqua is rising.' },
  { id: 'pg9', title: 'Pokémon Emerald', price: 45.99, category: 'games', image: '/assets/games/game_emerald.jpg', description: 'Rayquaza descends.' },
  { id: 'pg10', title: 'Pokémon FireRed', price: 49.99, category: 'games', image: '/assets/games/game_firered.jpg', description: 'Return to Kanto in color.' },
  { id: 'pg11', title: 'Pokémon LeafGreen', price: 49.99, category: 'games', image: '/assets/games/game_leafgreen.jpg', description: 'Kanto remade.' },
  { id: 'pg12', title: 'Pokémon Diamond', price: 39.99, category: 'games', image: '/assets/games/game_diamond.jpg', description: 'Dialga controls time.' },
  { id: 'pg13', title: 'Pokémon Pearl', price: 39.99, category: 'games', image: '/assets/games/game_pearl.jpg', description: 'Palkia warps space.' },
  { id: 'pg14', title: 'Pokémon Platinum', price: 49.99, category: 'games', image: '/assets/games/game_platinum.png', description: 'The Distortion World.' },
  { id: 'pg15', title: 'Pokémon HeartGold', price: 59.99, category: 'games', image: '/assets/games/game_heartgold.jpg', description: 'Johto remastered.' },
  { id: 'pg16', title: 'Pokémon SoulSilver', price: 59.99, category: 'games', image: '/assets/games/game_soulsilver.jpg', description: 'Lugia returns.' },
  { id: 'pg17', title: 'Pokémon Black', price: 49.99, category: 'games', image: '/assets/games/game_black.jpg', description: 'Truth vs Ideals.' },
  { id: 'pg18', title: 'Pokémon White', price: 49.99, category: 'games', image: '/assets/games/game_white.webp', description: 'Reshiram vs Zekrom.' },
  { id: 'pg19', title: 'Pokémon Black 2', price: 59.99, category: 'games', image: '/assets/games/game_black2.webp', description: 'Unova two years later.' },
  { id: 'pg20', title: 'Pokémon White 2', price: 59.99, category: 'games', image: '/assets/games/pokemon_white2.webp', description: 'The sequel to White.' },
  { id: 'pg21', title: 'Pokémon X', price: 39.99, category: 'games', image: '/assets/games/game_x.jpg', description: 'Mega Evolution arrives.' },
  { id: 'pg22', title: 'Pokémon Y', price: 39.99, category: 'games', image: '/assets/games/game_y.jpg', description: 'Yveltal takes flight.' },
  { id: 'pg23', title: 'Pokémon Omega Ruby', price: 39.99, category: 'games', image: '/assets/games/game_omegaruby.jpg', description: 'Primal Groudon.' },
  { id: 'pg24', title: 'Pokémon Alpha Sapphire', price: 39.99, category: 'games', image: '/assets/games/game_alphasapphire.jpg', description: 'Primal Kyogre.' },
  { id: 'pg25', title: 'Pokémon Sun', price: 39.99, category: 'games', image: '/assets/games/game_sun.jpg', description: 'Welcome to Alola.' },
  { id: 'pg26', title: 'Pokémon Moon', price: 39.99, category: 'games', image: '/assets/games/game_moon.jpg', description: 'Nighttime adventures.' },
  { id: 'pg27', title: 'Pokémon Ultra Sun', price: 44.99, category: 'games', image: '/assets/games/game_ultrasun.jpg', description: 'Necrozma strikes.' },
  { id: 'pg28', title: 'Pokémon Ultra Moon', price: 44.99, category: 'games', image: '/assets/games/game_ultramoon.webp', description: 'Alola expanded.' },
  { id: 'pg29', title: 'Pokémon Let\'s Go Pikachu', price: 59.99, category: 'games', image: '/assets/games/game_letsgopikachu.jpg', description: 'Classic adventure reimagined.' },
  { id: 'pg30', title: 'Pokémon Let\'s Go Eevee', price: 59.99, category: 'games', image: '/assets/games/game_letsgoeevee.png', description: 'Cute companion Eevee.' },
  { id: 'pg31', title: 'Pokémon Sword', price: 59.99, category: 'games', image: '/assets/games/game_sword.webp', description: 'Galar region journey.' },
  { id: 'pg32', title: 'Pokémon Shield', price: 59.99, category: 'games', image: '/assets/games/game_shield.webp', description: 'Defend Galar.' },
  { id: 'pg33', title: 'Pokémon Brilliant Diamond', price: 59.99, category: 'games', image: '/assets/games/game_brilliantdiamond.png', description: 'Sinnoh remade.' },
  { id: 'pg34', title: 'Pokémon Shining Pearl', price: 59.99, category: 'games', image: '/assets/games/game_shinningpearl.png', description: 'Palkia shines.' },
  { id: 'pg35', title: 'Pokémon Legends: Arceus', price: 59.99, category: 'games', image: '/assets/games/game_arceus.jpg', description: 'Ancient Sinnoh history.' },
  { id: 'pg36', title: 'Pokémon Scarlet', price: 59.99, category: 'games', image: '/assets/games/game_scarlet.jpg', description: 'Open world Paldea.' },
  { id: 'pg37', title: 'Pokémon Violet', price: 59.99, category: 'games', image: '/assets/games/game_violet.jpg', description: 'Future technology.' },
  { id: 'pg38', title: 'Pokémon Legends: Z-A', price: 59.99, category: 'games', image: '/assets/games/game_za.jpg', description: 'Return to Kalos.' },

  // DLC
  { id: 'pd1', title: 'Scarlet & Violet DLC', price: 34.99, category: 'dlc', image: '/assets/dlc/dlc_scarletviolet.jpg', description: 'Hidden Treasure of Area Zero.' },
  { id: 'pd2', title: 'Sword & Shield DLC', price: 29.99, category: 'dlc', image: '/assets/dlc/dlc_swordshield.jpg', description: 'Expansion Pass.' },
  { id: 'pd3', title: 'Legends Z-A DLC', price: 29.99, category: 'dlc', image: '/assets/dlc/dlc_ZA.jpg', description: 'Future content for Z-A.' },

  // Plush
  { id: 'pp1', title: 'Absol Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_absol.jpg', description: 'Dark type disaster warner.' },
  { id: 'pp2', title: 'Ampharos Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_ampharos.jpg', description: 'Electric light.' },
  { id: 'pp3', title: 'Arcanine Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_arcanine.jpg', description: 'Legendary fire dog.' },
  { id: 'pp4', title: 'Buizel Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_buizel.jpg', description: 'Sea weasel.' },
  { id: 'pp5', title: 'Celebi Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_celebi.jpg', description: 'Time travel fairy.' },
  { id: 'pp6', title: 'Chespin Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_chespin.jpg', description: 'Spiky nut.' },
  { id: 'pp7', title: 'Cinccino Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_cinccino.jpg', description: 'Scarf pokémon.' },
  { id: 'pp8', title: 'Cubone Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_cubone.jpg', description: 'Lonely pokémon.' },
  { id: 'pp9', title: 'Cyndaquil Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_cyndaquil.jpg', description: 'Fire mouse.' },
  { id: 'pp10', title: 'Ditto Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_ditto.jpg', description: 'Transform master.' },
  { id: 'pp11', title: 'Eevee Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_eevee.jpg', description: 'Evolution potential.' },
  { id: 'pp12', title: 'Fennekin Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_fennekin.jpg', description: 'Fox pokémon.' },
  { id: 'pp13', title: 'Flareon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_flareon.jpg', description: 'Flame pokémon.' },
  { id: 'pp14', title: 'Floatzel Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_floatzel.jpg', description: 'Sea weasel evolved.' },
  { id: 'pp15', title: 'Glaceon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_glaceon.jpg', description: 'Fresh snow pokémon.' },
  { id: 'pp16', title: 'Hoopa Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_hoopa.jpg', description: 'Mischief pokémon.' },
  { id: 'pp17', title: 'Jigglypuff Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_jigglypuff.jpg', description: 'Balloon pokémon.' },
  { id: 'pp18', title: 'Jirachi Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_jirachi.jpg', description: 'Wish maker.' },
  { id: 'pp19', title: 'Jolteon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_jolteon.jpg', description: 'Lightning pokémon.' },
  { id: 'pp20', title: 'Keldeo Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_keldeo.jpg', description: 'Colt pokémon.' },
  { id: 'pp21', title: 'Lapras Plush', price: 39.99, category: 'plush', image: '/assets/plush/plush_lapras.jpg', description: 'Transport pokémon.' },
  { id: 'pp22', title: 'Leafeon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_leafeon.jpg', description: 'Verdant pokémon.' },
  { id: 'pp23', title: 'Liepard Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_liepard.jpg', description: 'Cruel pokémon.' },
  { id: 'pp24', title: 'Litten Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_litten.jpg', description: 'Fire cat.' },
  { id: 'pp25', title: 'Litwick Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_litwick.jpg', description: 'Candle pokémon.' },
  { id: 'pp26', title: 'Lycanroc Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_lycanroc.jpg', description: 'Wolf pokémon (Midnight).' },
  { id: 'pp27', title: 'Lycanroc Midday Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_lycanrocmidday.jpg', description: 'Wolf pokémon (Midday).' },
  { id: 'pp28', title: 'Marshadow Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_marshadow.jpg', description: 'Gloomdweller.' },
  { id: 'pp29', title: 'Mew Plush', price: 39.99, category: 'plush', image: '/assets/plush/plush_mew.jpg', description: 'New species.' },
  { id: 'pp30', title: 'Mimikyu Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_mimikyu.jpg', description: 'Disguise pokémon.' },
  { id: 'pp31', title: 'Mudbray Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_mudbray.jpg', description: 'Donkey pokémon.' },
  { id: 'pp32', title: 'Noibat Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_noibat.jpg', description: 'Sound wave.' },
  { id: 'pp33', title: 'Oshawott Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_oshawott.jpg', description: 'Sea otter.' },
  { id: 'pp34', title: 'Pichu Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_pichu.jpg', description: 'Tiny mouse.' },
  { id: 'pp35', title: 'Piplup Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_piplup.jpg', description: 'Penguin pokémon.' },
  { id: 'pp36', title: 'Popplio Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_popplio.jpg', description: 'Sea lion.' },
  { id: 'pp37', title: 'Purrloin Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_purrloin.jpg', description: 'Devious pokémon.' },
  { id: 'pp38', title: 'Raichu Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_raichu.jpg', description: 'Electric mouse evolved.' },
  { id: 'pp39', title: 'Alolan Raichu Plush', price: 29.99, category: 'plush', image: '/assets/plush/plush_raichualola.jpg', description: 'Surfing Raichu.' },
  { id: 'pp40', title: 'Rockruff Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_rockruff.jpg', description: 'Puppy pokémon.' },
  { id: 'pp41', title: 'Rowlet Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_rowlet.jpg', description: 'Grass quill.' },
  { id: 'pp42', title: 'Shaymin Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_shaymin.jpg', description: 'Gratitude pokémon.' },
  { id: 'pp43', title: 'Sky Shaymin Plush', price: 34.99, category: 'plush', image: '/assets/plush/plush_shayminsky.jpg', description: 'Sky form.' },
  { id: 'pp44', title: 'Shinx Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_shinx.jpg', description: 'Flash pokémon.' },
  { id: 'pp45', title: 'Sylveon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_sylveon.jpg', description: 'Intertwining pokémon.' },
  { id: 'pp46', title: 'Togedemaru Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_togedemaru.jpg', description: 'Roly-poly pokémon.' },
  { id: 'pp47', title: 'Umbreon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_umbreon.jpg', description: 'Moonlight pokémon.' },
  { id: 'pp48', title: 'Vaporeon Plush', price: 24.99, category: 'plush', image: '/assets/plush/plush_vaporeon.jpg', description: 'Bubble jet pokémon.' },
  { id: 'pp49', title: 'Victini Plush', price: 39.99, category: 'plush', image: '/assets/plush/plush_victini.jpg', description: 'Victory pokémon.' },
  { id: 'pp50', title: 'Vulpix Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_vulpix.jpg', description: 'Fox pokémon.' },
  { id: 'pp51', title: 'Wooper Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_wooper.jpg', description: 'Water fish.' },
  { id: 'pp52', title: 'Wynaut Plush', price: 19.99, category: 'plush', image: '/assets/plush/plush_wynaut.jpg', description: 'Bright pokémon.' },
  { id: 'pp53', title: 'Zeraora Plush', price: 39.99, category: 'plush', image: '/assets/plush/plush_zeraora.jpg', description: 'Thunderclap.' },
  { id: 'pp54', title: 'Zorua Plush', price: 22.99, category: 'plush', image: '/assets/plush/plush_zorua.jpg', description: 'Tricky fox.' },
  { id: 'pp55', title: 'Meowstic Plush', price: 24.99, category: 'plush', image: '/assets/plush/plus_meowstic.jpg', description: 'Constraint pokémon.' },

  // Socks
  { id: 'ps1', title: 'Eevee Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_eevee.jpg', description: 'Cozy Eevee pattern.' },
  { id: 'ps2', title: 'Espeon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_espeon.jpg', description: 'Psychic style.' },
  { id: 'ps3', title: 'Flareon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_flareon.jpg', description: 'Warm and fiery.' },
  { id: 'ps4', title: 'Glaceon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_glaceon.jpg', description: 'Cool comfort.' },
  { id: 'ps5', title: 'Jolteon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_jolteon.jpg', description: 'Electric vibe.' },
  { id: 'ps6', title: 'Leafeon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_leafeon.jpg', description: 'Natural feeling.' },
  { id: 'ps7', title: 'Sylveon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_sylveon.jpg', description: 'Fairy cute.' },
  { id: 'ps8', title: 'Umbreon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_umbreon.jpg', description: 'Night mode.' },
  { id: 'ps9', title: 'Vaporeon Socks', price: 9.99, category: 'socks', image: '/assets/socks/socks_vaporeon.jpg', description: 'Splashy design.' },

  // Tops
  { id: 'pt1', title: 'Arcanine Tee', price: 24.99, category: 'tops', image: '/assets/tops/top_arcanine.jpg', description: 'Legendary style.' },
  { id: 'pt2', title: 'Friends & Foliage Tee', price: 22.99, category: 'tops', image: '/assets/tops/top_friendsfoliage.jpg', description: 'Nature lovers.' },
  { id: 'pt3', title: 'Glaceon Top', price: 24.99, category: 'tops', image: '/assets/tops/top_glaceon.jpg', description: 'Chilly fashion.' },
  { id: 'pt4', title: 'Jirachi Tee', price: 25.99, category: 'tops', image: '/assets/tops/top_jirachi.jpg', description: 'Wish upon a star.' },
  { id: 'pt5', title: 'Jirachi Special Top', price: 27.99, category: 'tops', image: '/assets/tops/top_jirachi2.jpg', description: 'Sparkling design.' },
  { id: 'pt6', title: 'Lapras Top', price: 26.99, category: 'tops', image: '/assets/tops/top_lapras.jpg', description: 'Sea voyager.' },
  { id: 'pt7', title: 'Leafeon Top', price: 24.99, category: 'tops', image: '/assets/tops/top_leafeon.jpg', description: 'Green aesthetic.' },
  { id: 'pt8', title: 'Lucario Top', price: 26.99, category: 'tops', image: '/assets/tops/top_lucario.jpg', description: 'Aura master.' },
  { id: 'pt9', title: 'Mega Charizard Top', price: 29.99, category: 'tops', image: '/assets/tops/top_mega charizard.jpg', description: 'Mega power.' },
  { id: 'pt10', title: 'Mimikyu Top', price: 24.99, category: 'tops', image: '/assets/tops/top_mimikyu.jpg', description: 'Spooky friend.' },
  { id: 'pt11', title: 'Ninetales Top', price: 25.99, category: 'tops', image: '/assets/tops/top_ninetales.jpg', description: 'Elegant fire.' },
  { id: 'pt12', title: 'Sylveon Top', price: 24.99, category: 'tops', image: '/assets/tops/top_sylveon.jpg', description: 'Fairy ribbon.' },
  { id: 'pt13', title: 'Tropical Top', price: 22.99, category: 'tops', image: '/assets/tops/top_tropical.jpg', description: 'Summer vibes.' },
  { id: 'pt14', title: 'Tropical Dreamy Top', price: 23.99, category: 'tops', image: '/assets/tops/top_tropicaldreamy.jpg', description: 'Island life.' },
  { id: 'pt15', title: 'Umbreon Top', price: 24.99, category: 'tops', image: '/assets/tops/top_umbreon.jpg', description: 'Dark moon.' },
  { id: 'pt16', title: 'Zorua Top', price: 23.99, category: 'tops', image: '/assets/tops/top_zorua.jpg', description: 'Fox illusion.' },

  // Bottoms
  { id: 'pb1', title: 'Glimwood Bottoms', price: 34.99, category: 'bottom', image: '/assets/bottom/bottom glimwood.jpg', description: 'Mystic forest style.' },
  { id: 'pb2', title: 'Sylveon Shorts', price: 29.99, category: 'bottom', image: '/assets/bottom/bottom sylveon.jpg', description: 'Cute ribbons.' },
  { id: 'pb3', title: 'Friends & Foliage Shorts', price: 29.99, category: 'bottom', image: '/assets/bottom/bottom_friendsfoliage.jpg', description: 'Garden party.' },
  { id: 'pb4', title: 'Jigglypuff Leggings', price: 32.99, category: 'bottom', image: '/assets/bottom/bottom_jigglypuff.jpg', description: 'Sing along.' },
  { id: 'pb5', title: 'Pikachu Joggers', price: 39.99, category: 'bottom', image: '/assets/bottom/bottom_pikachu.jpg', description: 'Electric speed.' },
  { id: 'pb6', title: 'Tropical Bottoms', price: 34.99, category: 'bottom', image: '/assets/bottom/bottom_tropical.jpg', description: 'Beach ready.' },
  { id: 'pb7', title: 'Tropical Dreamy Shorts', price: 29.99, category: 'bottom', image: '/assets/bottom/bottom_tropicaldreamy.jpg', description: 'Vacation mode.' },
  { id: 'pb8', title: 'Zorua Pants', price: 36.99, category: 'bottom', image: '/assets/bottom/bottom_zorua.jpg', description: 'Shadow walker.' },
];

export const getPokemonProducts = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
        resolve(pokemonProducts);
    }, 500); // Simulate network delay
  });
};
